import re

with open('server.js', 'r', encoding='utf-8') as f:
    js = f.read()

# I used `html = html.replace(/93998164-01-TNU8/g, record.reference);`
# But if he says "The page Reference: should display the one entered in admin, but it's currently wrong."
# What is it displaying? Is it displaying nothing? Or the wrong number?
# Wait! Does the original HTML literally contain the text "Reference: 93998164-01-TNU8"?
# Or is it dynamically generated by JS?
# Let's search the HTML.
with open('verification.othm.org.uk/index.html', 'r', encoding='utf-8') as f2:
    html = f2.read()

match = re.search(r'Reference:.*?\n.*', html, flags=re.IGNORECASE)
if match:
    print("Found reference text:")
    print(match.group(0))
else:
    print("No literal 'Reference:' text found in index.html.")

